let input=document.getElementById("numOfwords");

const container=document.querySelector(".container");

const generateWord=(n)=>{ // returns word created of a specific size passed to the parameter. 
    let text="";
    const letters="ABCDEFGHIJKLMNOPQRSTUVWXYZ"; // word is generated by randomly selecting character from this letters variable.
    for(let i=0;i<n;++i){
        const random=(Math.random()*25).toFixed(0); // randomly a char is choosen and text stores that char one by one until text of n size not created.
        text+=letters[random]; 
    }
    return text;
};

let numOfwords;
const generatePara=()=>{
    numOfwords=Number(input.value); // the input given by user to input tag is stored.

    let data=""; // data which will be the output is initialized to empty string.

    var para=document.createElement("p"); // the output para is created.

    for(let i=0;i<numOfwords;++i){ // loop starting with 0 to input user gave for amount of words.
        const randomNumber=(Math.random()*(10-2)+2).toFixed(0);// a random number is called for a random size of word between 10 to 2.
        data+=generateWord(randomNumber);// the generateWord function is called and the text which is returned from there is stored in "data".
        data+=" "; // after a word is stored blank space is stored at the end for better readability.
    }

    console.log(data);
    para.textContent=data; // the final group of words of user input size is now content of para class of p tag.

    para.setAttribute("class","paras"); // the css defined for the ouput is called by assigning paras class to para .

    para.setAttribute("id","pp"); // the id of pp is assigned to para so that it can be cleared from the screen by clears function whenever needed.

    container.append(para); // the p tag which is our required output is now part of container div and output now can be shown on screen.
}

function clears(){ //clear the p tag and also make input to 0.
    document.getElementById("pp").remove();
    input.value="0";
}